# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\wii03\Desktop\yt_dlp2\download_tab\video_subwindow\video.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1130, 826)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        Form.setFont(font)
        Form.setStyleSheet("QWidget {\n"
"    background-color: #F0F4F4;\n"
"    color: #2E7D32;\n"
"}\n"
"\n"
"/* QLabel settings */\n"
"QLabel {\n"
"    color: #2E7D32;\n"
"}\n"
"\n"
"/* QPushButton settings */\n"
"QPushButton {\n"
"    background-color: #A5D6A7;\n"
"    border: 1px solid #81C784;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #81C784;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #4CAF50;\n"
"}\n"
"\n"
"/* QTableWidget settings */\n"
"QTableWidget {\n"
"    background-color: #FFFFFF;\n"
"    alternate-background-color: #E8F5E9;  /* 表格的交替行背景颜色 */\n"
"    gridline-color: #A5D6A7;   /* 網格線 */\n"
"    selection-background-color: #A5D6A7;\n"
"    border: 1px solid #81C784;\n"
"}\n"
"QTableWidget::item {\n"
"    border: 1px solid #81C784;\n"
"    padding: 2px;\n"
"}\n"
"QTableWidget::item::selected{\n"
"    color:white;\n"
"    background:#609d78;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #426c54;\n"
"    color: white;\n"
"    padding: 4px;\n"
"    border: 1px solid #81C784;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.video_audio_lbl = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.video_audio_lbl.setFont(font)
        self.video_audio_lbl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.video_audio_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.video_audio_lbl.setObjectName("video_audio_lbl")
        self.verticalLayout.addWidget(self.video_audio_lbl)
        self.video_audio_table = QtWidgets.QTableWidget(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.video_audio_table.setFont(font)
        self.video_audio_table.setObjectName("video_audio_table")
        self.video_audio_table.setColumnCount(12)
        self.video_audio_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.video_audio_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.video_audio_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.video_audio_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.video_audio_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.video_audio_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.video_audio_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.video_audio_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.video_audio_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.video_audio_table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.video_audio_table.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.video_audio_table.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.video_audio_table.setHorizontalHeaderItem(11, item)
        self.video_audio_table.horizontalHeader().setDefaultSectionSize(90)
        self.video_audio_table.horizontalHeader().setSortIndicatorShown(True)
        self.verticalLayout.addWidget(self.video_audio_table)
        self.video_lbl = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.video_lbl.setFont(font)
        self.video_lbl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.video_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.video_lbl.setObjectName("video_lbl")
        self.verticalLayout.addWidget(self.video_lbl)
        self.video_table = QtWidgets.QTableWidget(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.video_table.setFont(font)
        self.video_table.setObjectName("video_table")
        self.video_table.setColumnCount(12)
        self.video_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.video_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.video_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.video_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.video_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.video_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.video_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.video_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.video_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.video_table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.video_table.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.video_table.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.video_table.setHorizontalHeaderItem(11, item)
        self.video_table.horizontalHeader().setDefaultSectionSize(90)
        self.video_table.horizontalHeader().setSortIndicatorShown(True)
        self.video_table.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout.addWidget(self.video_table)
        self.audio_lbl = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.audio_lbl.setFont(font)
        self.audio_lbl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.audio_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.audio_lbl.setObjectName("audio_lbl")
        self.verticalLayout.addWidget(self.audio_lbl)
        self.audio_table = QtWidgets.QTableWidget(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.audio_table.setFont(font)
        self.audio_table.setObjectName("audio_table")
        self.audio_table.setColumnCount(12)
        self.audio_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.audio_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.audio_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.audio_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.audio_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.audio_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.audio_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.audio_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.audio_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.audio_table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.audio_table.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.audio_table.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.audio_table.setHorizontalHeaderItem(11, item)
        self.audio_table.horizontalHeader().setDefaultSectionSize(90)
        self.audio_table.horizontalHeader().setSortIndicatorShown(True)
        self.audio_table.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout.addWidget(self.audio_table)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.default_lbl = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.default_lbl.setFont(font)
        self.default_lbl.setText("")
        self.default_lbl.setObjectName("default_lbl")
        self.horizontalLayout.addWidget(self.default_lbl)
        self.ok_btn = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ok_btn.sizePolicy().hasHeightForWidth())
        self.ok_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.ok_btn.setFont(font)
        self.ok_btn.setObjectName("ok_btn")
        self.horizontalLayout.addWidget(self.ok_btn)
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Video Source"))
        self.video_audio_lbl.setText(_translate("Form", "Video & Audio"))
        item = self.video_audio_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "ID"))
        item = self.video_audio_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "EXT"))
        item = self.video_audio_table.horizontalHeaderItem(3)
        item.setText(_translate("Form", "RESOLUTION"))
        item = self.video_audio_table.horizontalHeaderItem(4)
        item.setText(_translate("Form", "FPS"))
        item = self.video_audio_table.horizontalHeaderItem(5)
        item.setText(_translate("Form", "FILESIZE"))
        item = self.video_audio_table.horizontalHeaderItem(6)
        item.setText(_translate("Form", "TBR"))
        item = self.video_audio_table.horizontalHeaderItem(7)
        item.setText(_translate("Form", "PROTOCOL"))
        item = self.video_audio_table.horizontalHeaderItem(8)
        item.setText(_translate("Form", "VCODEC"))
        item = self.video_audio_table.horizontalHeaderItem(9)
        item.setText(_translate("Form", "VBR"))
        item = self.video_audio_table.horizontalHeaderItem(10)
        item.setText(_translate("Form", "ACODEC"))
        item = self.video_audio_table.horizontalHeaderItem(11)
        item.setText(_translate("Form", "ABR"))
        self.video_lbl.setText(_translate("Form", "Video"))
        item = self.video_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "ID"))
        item = self.video_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "EXT"))
        item = self.video_table.horizontalHeaderItem(3)
        item.setText(_translate("Form", "RESOLUTION"))
        item = self.video_table.horizontalHeaderItem(4)
        item.setText(_translate("Form", "FPS"))
        item = self.video_table.horizontalHeaderItem(5)
        item.setText(_translate("Form", "FILESIZE"))
        item = self.video_table.horizontalHeaderItem(6)
        item.setText(_translate("Form", "TBR"))
        item = self.video_table.horizontalHeaderItem(7)
        item.setText(_translate("Form", "PROTOCOL"))
        item = self.video_table.horizontalHeaderItem(8)
        item.setText(_translate("Form", "VCODEC"))
        item = self.video_table.horizontalHeaderItem(9)
        item.setText(_translate("Form", "VBR"))
        item = self.video_table.horizontalHeaderItem(10)
        item.setText(_translate("Form", "ACODEC"))
        item = self.video_table.horizontalHeaderItem(11)
        item.setText(_translate("Form", "ABR"))
        self.audio_lbl.setText(_translate("Form", "Audio"))
        item = self.audio_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "ID"))
        item = self.audio_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "EXT"))
        item = self.audio_table.horizontalHeaderItem(3)
        item.setText(_translate("Form", "RESOLUTION"))
        item = self.audio_table.horizontalHeaderItem(4)
        item.setText(_translate("Form", "FPS"))
        item = self.audio_table.horizontalHeaderItem(5)
        item.setText(_translate("Form", "FILESIZE"))
        item = self.audio_table.horizontalHeaderItem(6)
        item.setText(_translate("Form", "TBR"))
        item = self.audio_table.horizontalHeaderItem(7)
        item.setText(_translate("Form", "PROTOCOL"))
        item = self.audio_table.horizontalHeaderItem(8)
        item.setText(_translate("Form", "VCODEC"))
        item = self.audio_table.horizontalHeaderItem(9)
        item.setText(_translate("Form", "VBR"))
        item = self.audio_table.horizontalHeaderItem(10)
        item.setText(_translate("Form", "ACODEC"))
        item = self.audio_table.horizontalHeaderItem(11)
        item.setText(_translate("Form", "ABR"))
        self.ok_btn.setText(_translate("Form", "OK !"))
